# Modulo 3: Ejercicio 1
## Alumno: Jose Suarez

### 1. Crear un vector con valores dentro del rango 10 a 49.

In [1]:
import numpy as np

vector = np.linspace(10, 50, 14)
print(vector)

[10.         13.07692308 16.15384615 19.23076923 22.30769231 25.38461538
 28.46153846 31.53846154 34.61538462 37.69230769 40.76923077 43.84615385
 46.92307692 50.        ]


### 2. Invertir el vector anterior

In [2]:
vectorInvertido = np.flip(vector)
print(vectorInvertido)

[50.         46.92307692 43.84615385 40.76923077 37.69230769 34.61538462
 31.53846154 28.46153846 25.38461538 22.30769231 19.23076923 16.15384615
 13.07692308 10.        ]


### 3. Crear una matriz con valores de 0 a 8

In [3]:
matriz = np.array([np.linspace(0, 8, 5), np.linspace(0, 8, 5), np.linspace(0, 8, 5)])
print(matriz)

[[0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]]


### 4. Encontrar los índices que no son 0 en el arreglo
[1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [4]:
vector4 = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
print(vector4)

condicion = vector4 != 0
print(condicion)

seleccion = vector4[condicion] 
print(seleccion)

[ 1  2  4  2  4  0  1  0  0  0 12  4  5  6  7  0]
[ True  True  True  True  True False  True False False False  True  True
  True  True  True False]
[ 1  2  4  2  4  1 12  4  5  6  7]


### 5. Crear una matriz identidad de 6x6

In [5]:
identy6x6 = np.eye(6)
print(identy6x6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### 6. Crear una matriz con valores al azar con forma 3x3x3

In [6]:
aleatoria = np.random.rand(3, 3, 3)
print(aleatoria)

[[[0.88548253 0.95612112 0.83544453]
  [0.38602185 0.48880644 0.48904595]
  [0.45750898 0.88255211 0.49897205]]

 [[0.35623349 0.8789546  0.50033249]
  [0.13088361 0.84626792 0.9894707 ]
  [0.4306919  0.54739503 0.9461414 ]]

 [[0.36067812 0.42749806 0.95774522]
  [0.78780593 0.01178192 0.56567298]
  [0.22944557 0.61839309 0.51989064]]]


### 7. Crea un arreglo NumPy de tamaño 5x5 lleno de ceros.

In [7]:
zerony = np.zeros((5, 5))
print(zerony)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 8. Crea un arreglo NumPy de tamaño 3x3 lleno de unos.

In [8]:
uniano = np.ones((3, 3))
print(uniano)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 9. Crea dos arreglos NumPy de tamaño 2x2 con valores aleatorios. Realiza la suma, resta, multiplicación y división de los arreglos creados.

In [9]:
arreglin_1 = np.random.rand(2,2)
arreglin_2 = np.random.rand(2,2)
print(arreglin_1)
print("-" * 30)
print(arreglin_2)
print("-" * 30)


print("suma")
print(arreglin_1 + arreglin_2)
print("-" * 30)

print("resta")
print(arreglin_1 - arreglin_2)
print("-" * 30)

print("multiplicacion")
print(arreglin_1 * arreglin_2)
print("-" * 30)

print("division")
print(arreglin_1 / arreglin_2)

[[0.92097357 0.89906236]
 [0.67690432 0.1316877 ]]
------------------------------
[[0.60798791 0.2253464 ]
 [0.63456262 0.28337987]]
------------------------------
suma
[[1.52896147 1.12440876]
 [1.31146694 0.41506757]]
------------------------------
resta
[[ 0.31298566  0.67371596]
 [ 0.0423417  -0.15169216]]
------------------------------
multiplicacion
[[0.55994079 0.20260047]
 [0.42953818 0.03731764]]
------------------------------
division
[[1.51478928 3.98969037]
 [1.06672581 0.46470381]]


### 10. Crea un vector con valores entre 0 y 10, con intervalos de 0.5.

In [10]:
vector_10 = np.arange(0, 10, .5)
print(vector_10)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


### 11. Genera una matriz de tamaño 5x5 con valores aleatorios enteros entre 1 y 100.

In [11]:
rng = np.random.default_rng()

random5x5 = rng.integers(1, 101, size=(5, 5))
print(random5x5)

[[65 53 26 30 82]
 [86 52 62 83 53]
 [45 51 80 22 57]
 [64  1 92 94 98]
 [31 76 28 99 90]]


### 12. Crea un arreglo NumPy unidimensional de 10 elementos.

In [12]:
vector_12 = np.linspace(0, 1, 10)
print(vector_12)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### 13. Imprime el primer elemento del arreglo anterior.

In [13]:
print(vector_12[0])

0.0


### 14. Imprime los últimos 3 elementos del arreglo anterior.

In [14]:
print(vector_12[-3:])

[0.77777778 0.88888889 1.        ]


### 15. Imprime los elementos del índice 3 al 7 anterior.

In [15]:
print(vector_12[3:8])

[0.33333333 0.44444444 0.55555556 0.66666667 0.77777778]


### 16. Cambia el valor del índice 5 por 20 en el arreglo anterior.

In [16]:
vector_12[5] = 20
print(vector_12)

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444 20.
  0.66666667  0.77777778  0.88888889  1.        ]


### 17. Crea un arreglo NumPy con números del 1 al 10.

In [17]:
arreglo_17 = np.arange(1, 11)
print(arreglo_17)

[ 1  2  3  4  5  6  7  8  9 10]


### 18. Calcula la suma, el promedio, la desviación estándar y el máximo valor del arreglo del ejercicio anterior.

In [25]:
print(arreglo_17.sum())
print(np.average(arreglo_17))
print(np.std(arreglo_17))
print(np.max(arreglo_17))

55
5.5
2.8722813232690143
10


### 19. Crear un arreglo con elementos del 1 al 10 y seleccionar solo los pares


In [30]:
arreglo_19 = np.arange(1,10)
print(arreglo_19)
condicion = arreglo_19 % 2 == 0
print(arreglo_19[condicion])

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


### 20. Calcula la suma, la media, el máximo y el mínimo de los valores de
seno, coseno y tangente para un conjunto de ángulos en grados.


In [38]:
angulosGrados = np.array([0, 30, 45, 60, 90])
print(angulosGrados)

print("Para los seno: ")
senoAngulos = np.sin(angulosGrados)
print(senoAngulos)
print(np.sum(senoAngulos))
print(np.median(senoAngulos))
print(np.max(senoAngulos))
print(np.min(senoAngulos))

print("Para los coseno: ")
cosenoAngulos = np.cos(angulosGrados)
print(cosenoAngulos)
print(np.sum(cosenoAngulos))
print(np.median(cosenoAngulos))
print(np.max(cosenoAngulos))
print(np.min(cosenoAngulos))

print("Para las tangentes: ")
tanAngulos = np.tan(angulosGrados)
print(tanAngulos)
print(np.sum(tanAngulos))
print(np.median(tanAngulos))
print(np.max(tanAngulos))
print(np.min(tanAngulos))


[ 0 30 45 60 90]
Para los seno: 
[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
0.4520579429395978
0.0
0.8939966636005579
-0.9880316240928618
Para los coseno: 
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
0.2790868421609874
0.15425144988758405
1.0
-0.9524129804151563
Para las tangentes: 
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]
-6.460716028931094
0.0
1.6197751905438615
-6.405331196646276
